name: nugawiki

services:
  wiki:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NOTION_TOKEN: ${NOTION_TOKEN}
        NOTION_DB_ID: ${NOTION_DB_ID}
    image: nugawiki:latest
    container_name: nugawiki
    restart: unless-stopped
    ports:
      - "${PROD_PORT:-1729}:80"
